```css
.mom {
/* Frame 1 */

position: absolute;
width: 75px;
height: 50px;
left: 0px;
top: 0px;
}


.kid {
/* Rectangle 1 */

position: absolute;
left: 0%;
right: -3.17%;
top: 0%;
bottom: 0%;

background: #C4C4C4;
border: 3px solid #000000;
box-sizing: border-box;
box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 20px;
}
```

```html
<style>
.mom {
/* Frame 1 */

position: absolute;
width: 75px;
height: 50px;
left: 0px;
top: 0px;
}


.kid {
/* Rectangle 1 */

position: absolute;
left: 0%;
right: -3.17%;
top: 0%;
bottom: 0%;

background: #C4C4C4;
border: 3px solid #000000;
box-sizing: border-box;
box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 20px;
}
</style>
<div class="mom">
  <div class="kid">
  </div>
</div>
```

```{r}
tags$div(class = "mom",
 tags$div(class = "kid")) -> tag_element17

tag_element17 |> econWeb::browseTag2()

```

```html
<style>
.mom {
	/* .mom */
	
	position: relative;
	width: 152px;
	height: 94px;
	
	
	
}
.kid {
	/* .kid */
	
	position: absolute;
	width: 152px;
	height: 94px;
	left: 0px;
	top: 0px;
	
	background: #C4C4C4;
}
</style>
<div class='mom'>
  <div class="kid">
  </div>
</div>

```

```{r}
tagList(
tags$style('

.mom {
	/* .mom */
	
	position: relative;
	width: 152px;
	height: 94px;
	
	
	
}
.kid {
	/* .kid */
	
	position: absolute;
	width: 152px;
	height: 94px;
	left: 0px;
	top: 0px;
	
	background: #C4C4C4;
}

'),
tags$div(class = "mom",
 tags$div(class = "kid"))
) -> tag_element17

tag_element17 |> econWeb::browseTag2()

```

